<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    
    <!-- 버전 정보 -->
    <Version>3.3.0</Version>
    <AssemblyVersion>3.3.0.0</AssemblyVersion>
    <FileVersion>3.3.0.0</FileVersion>
    
    <!-- 어플리케이션 정보 -->
    <Product>FACTOVA Message Log Viewer</Product>
    <Company>FACTOVA</Company>
    <Authors>FACTOVA IT Team</Authors>
    <Description>FACTOVA 통신 로그 뷰어</Description>
    <Copyright>Copyright © FACTOVA 2025</Copyright>
    
    <!-- 빌드 설정 (Publish 시 적용) -->
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    
    <!-- 아이콘 설정 -->
    <ApplicationIcon>Icons\free-icon-search-10725247.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Include=".github\workflows\release.yml" />
  </ItemGroup>

  <!-- XAML 강제 재컴파일 -->
  <ItemGroup>
    <Page Update="TabSettingsWindow.xaml">
      <Generator>MSBuild:Compile</Generator>
      <XamlRuntime>Wpf</XamlRuntime>
    </Page>
    <Page Update="MainWindow.xaml">
      <Generator>MSBuild:Compile</Generator>
      <XamlRuntime>Wpf</XamlRuntime>
    </Page>
    <Page Update="Views\EventLogViewerControl.xaml">
      <Generator>MSBuild:Compile</Generator>
      <XamlRuntime>Wpf</XamlRuntime>
    </Page>
    <Page Update="Views\DataLogViewerControl.xaml">
      <Generator>MSBuild:Compile</Generator>
      <XamlRuntime>Wpf</XamlRuntime>
    </Page>
    <Page Update="Views\ExceptionLogViewerControl.xaml">
      <Generator>MSBuild:Compile</Generator>
      <XamlRuntime>Wpf</XamlRuntime>
    </Page>
    <Page Update="Views\FLLogViewerControl.xaml">
      <Generator>MSBuild:Compile</Generator>
      <XamlRuntime>Wpf</XamlRuntime>
    </Page>
    <Page Update="Views\DataLogViewerWindow.xaml">
      <Generator>MSBuild:Compile</Generator>
      <XamlRuntime>Wpf</XamlRuntime>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="EPPlus" Version="7.5.2" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Icons\free-icon-search-10725247.ico" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Views\" />
    <Folder Include="Popup\" />
  </ItemGroup>

</Project>
